apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-api-name-deployment
  labels:
    app: my-api-name
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-api-name
  template:
    metadata:
      labels:
        app: my-api-name
    spec:
      containers:
        - name: my-api-name
          image: jupsy/pokemon-api:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              cpu: 500m
              memory: 512Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30
