apiVersion: v1
kind: Service
metadata:
  name: my-api-name-service
  labels:
    app: my-api-name
spec:
  selector:
    app: my-api-name
  ports:
    -protocol: TCP
    port: 3000
    targetPort: 3000
  type: NodePort # # Service type : NodePort, ClusterIP, LoadBalancer
